version: "3.9"
services:
  postgres:
    image: postgres:16
    container_name: clipmind_postgres
    environment:
      POSTGRES_USER: clipmind
      POSTGRES_PASSWORD: clipmind
      POSTGRES_DB: clipmind_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: clipmind_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata: